/**
 * Robots.txt — /robots.txt
 *
 * Generated by Next.js 14 at build time.
 * Allows all crawlers on all paths; directs them to the sitemap.
 */

import type { MetadataRoute } from "next";

const BASE_URL =
  process.env.NEXT_PUBLIC_BASE_URL ?? "https://lorenacriado.dev";

export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
    },
    sitemap: `${BASE_URL}/sitemap.xml`,
    host: BASE_URL,
  };
}
