/**
 * Sitemap — /sitemap.xml
 *
 * Auto-generated by Next.js 14 at build time.
 * All static routes + dynamic project slugs are included.
 *
 * SEO architectural decision: sitemap is generated server-side at build time
 * (not client-side) so crawlers always see fresh content.
 */

import type { MetadataRoute } from "next";
import { getAllProjects } from "@/lib/data";

const BASE_URL =
  process.env.NEXT_PUBLIC_BASE_URL ?? "https://lorenacriado.dev";

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const projects = await getAllProjects();

  const staticRoutes: MetadataRoute.Sitemap = [
    {
      url: BASE_URL,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 1.0,
    },
    {
      url: `${BASE_URL}/about`,
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/projects`,
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/contact`,
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 0.7,
    },
  ];

  const projectRoutes: MetadataRoute.Sitemap = projects.map((p) => ({
    url: `${BASE_URL}/projects/${p.slug}`,
    lastModified: new Date(p.publishedAt),
    changeFrequency: "monthly" as const,
    priority: p.featured ? 0.8 : 0.6,
  }));

  return [...staticRoutes, ...projectRoutes];
}
